### ISSUE TITLE
Build out CRUD endpoints for datasets

### ISSUE THREAD

**Issue by chriswhong** [chriswhong/ReallySimpleOpenData#1]
Set up REST endpoints for individual datasets:

Should we just use the giant IDs created by mongodb, or come up with a shorter, URL-friendly way to address a dataset?

GET /datasets/:id

POST /datasets/:id

PUT /datasets/:id

DELETE /datasets/:id

**Comment by jfarid27** [comment]
@chriswhong Is the query request found on the mongodb in a collection called "dataset"?

**Comment by chriswhong** [comment]
I believe it is actually a collection called "Baltimore"... can't check until this evening, my dev laptop is at home.  Thanks for contributing.

**Comment by jfarid27** [comment]
I got started on the read request in 44e86f8ac9f7fd98398c44cbac0edceaa8d77b, but it's not clear what exactly is your data model. I think you're trying to make a collection that represents a "file" and the documents (the mondodb definition of document) in that collection are the data points people are interested in. It might be easier to just define a collection of datasets, have an ID and name for a dataset, but then have [embedded documents](http://docs.mongodb.org/manual/core/data-model-design/). It certainly would make the CRUD design much easier.

**Comment by chriswhong** [comment]
yes, collection is called baltimore.... database is called 'rsod'
